# Generated by Django 2.2.7 on 2020-04-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
