# Generated by Django 2.2.7 on 2020-04-24 21:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
