# Generated by Django 2.2.7 on 2020-04-21 20:59

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(default='job.png', upload_to=jobs.models.upload_location),
        ),
    ]
