# Generated by Django 2.2.7 on 2020-04-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200421_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjob',
            name='slug',
        ),
    ]
