# Generated by Django 2.2.7 on 2020-04-24 21:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_userjob_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='body',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True),
        ),
    ]
